# Generated by Django 5.2 on 2025-05-02 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensordata',
            name='sensor_id',
        ),
    ]
